version: '3.5'

services:
  tasks:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      - MICROSERVICE_NAME
      - MICROSERVICE_PORT
      - SPRING_PROFILES_ACTIVE
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - JOBS_DATASOURCE_USERNAME
      - JOBS_DATASOURCE_PASSWORD
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
      - ELASTIC_XPACKSECURITYUSER
      - JAVA_OPTS=-Xmx1g -Xss1g
    networks:
      - elastic-net
      - kafka-net
      - postgres-net
      - redmic-net
    volumes:
      - mediastorage-private-vol:/data/MEDIA_STORAGE
      - mediastorage-public-vol:/data/PUBLIC_MEDIA_STORAGE
    healthcheck:
      test: wget --spider -S -t 3 http://localhost:${MICROSERVICE_PORT}/api/${MICROSERVICE_NAME}/actuator/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m

networks:
  elastic-net:
    external: true
  kafka-net:
    external: true
  postgres-net:
    external: true
  redmic-net:
    external: true
