version: '3.5'

services:
  tasks:
    deploy:
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          memory: 1639M

volumes:
  mediastorage-private-vol:
    name: mediastorage-private-vol
    driver: "cloudstor:aws"
    driver_opts:
      backing: shared

  mediastorage-public-vol:
    name: mediastorage-public-vol
    driver: "cloudstor:aws"
    driver_opts:
      backing: shared
